branches:
  only:
    - master

cache: .tox

environment:
  SDL_VIDEODRIVER: dummy

  AWS_ACCESS_KEY_ID:
    secure: 3BNx+Qb95vjwu5E6CbX9mrQ8X4EboF4dzt9Ei7Wc4QU=

  AWS_SECRET_ACCESS_KEY:
    secure: bkPtYZvL3Asozn/udXEZChW2gqT/GEJ66xdf+OeMtn4faZR36uKoP2x+wgCp0enQ

  PYPI_TEST_USERNAME: __token__

  PYPI_TEST_PASSWORD:
    secure: > 
      ES1+Jf/JRtml7urHLDaPvnLhtt+unOq+xGbT7xl53qJ31yq2f/o9bj82eG4WFhDaDq2+dD55t
      5DW69oklIm2ePcDoMrW61gar5Wbnhe4a+pDAlS1qA0AJQkb2mOqq80Uqfn7fhZn7u0irgzrlq
      Tj22sBGkbUfzIPsG1HBzPfQof44JVO+mDmWQKEwmw1Wh4rf0ATWeVvIzWZazbjEnhlwbP7Uya
      2wrcJy8UUiAzatdEjRbLSuLSu52MCL8gS9s785KVF0u+8dH00Gaer1cx2dQnk35WtUmkdkzPO
      81Vm+q8=

  matrix:
    - job_name: Windows Tests
      appveyor_build_worker_image: Visual Studio 2019

    - job_name: macOS Tests and Load Artifacts
      appveyor_build_worker_image: macOS

matrix:
  fast_finish: true

build: off

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
for:
  -
    matrix:
      only:
        - job_name: Windows Tests

    install:
      - pip install tox

    test_script:
      - pwd
      - python build/splitversion.py --mode split
      - python -m tox
      - python build/splitversion.py --mode clean

  -
    matrix:
      only:
        - job_name: macOS Tests and Load Artifacts

    install:
      - pip install tox

    before_test:
      - export PATH=$PATH:~/venv3.5/bin/:~/venv3.6/bin/:~/venv3.7/bin/:~/venv3.8/bin/:~/venv3.9/bin/

    test_script:
      - python build/splitversion.py --mode split
      - python -m tox
      - python build/splitversion.py --mode clean

    after_test:
      - cd build
      - python release.py
