branches:
  only:
    - master

cache: .tox

environment:
  SDL_VIDEODRIVER: dummy

  AWS_ACCESS_KEY_ID:
    secure: 3BNx+Qb95vjwu5E6CbX9mrQ8X4EboF4dzt9Ei7Wc4QU=

  AWS_SECRET_ACCESS_KEY:
    secure: bkPtYZvL3Asozn/udXEZChW2gqT/GEJ66xdf+OeMtn4faZR36uKoP2x+wgCp0enQ

  matrix:
    - job_name: Windows Tests
      appveyor_build_worker_image: Visual Studio 2019

    - job_name: macOS Tests and Load Artifacts
      appveyor_build_worker_image: macOS

matrix:
  fast_finish: true

build: off

for:
  -
    matrix:
      only:
        - job_name: Windows Tests

    install:
      - pip install tox

    test_script:
      - python -m tox

  -
    matrix:
      only:
        - job_name: macOS Tests and Load Artifacts

    install:
      - pip install tox
      - pip install build twine

    before_test:
      - export PATH=$PATH:~/venv3.5/bin/:~/venv3.6/bin/:~/venv3.7/bin/:~/venv3.8/bin/:~/venv3.9/bin/

    test_script:
      - python -m tox

    after_test:
      - cd build
      - ./release.sh
