environment:
  SDL_VIDEODRIVER: dummy

  # Insert your device's public SSH key here to access the Mac build image.
  APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9Rkdcjvu0MQOMOqlpa5J757pso3iPzMOt6WK3WgJW0kZl/6l/UZfjN9fgJ6PXhtSQkXgyvOrhuyMVdIZIstdbZKnpC6KV274gof44653ildsK3wPSpuF2v9lmPPvfQWyHCfjb19T06p4Rh5idUmZqPXtMFNWL2vSR4IGBE90JlaNOdXDU07KPVkjbb5vsQLh/vl47N2LjU4vDCqHscQ+wVJuExE63vVuv2T3SDYJNpjAuvLZStdIjOjTyRaJHq2uazfajaKK1Ss3IUgvWnfFqg7WD9zASC9VffxZd9mvP1PtAODIPENdZWNFODsdIlSHTwAdO3DhWbwaDS+nfDhgB evan@Evans-MBP.wv.cc.cmu.edu


  matrix:
    - job_name: Windows Tests
      appveyor_build_worker_image: Visual Studio 2019

    - job_name: macOS Tests
      appveyor_build_worker_image: macOS

matrix:
  fast_finish: false

build: off

for:
  -
    matrix:
      only:
        - job_name: Windows Tests

    install:
      - C:\Python310\python.exe -m pip install tox twine build

    before_test:
      - C:\Python310\python.exe build/build.py

    test_script:
      # We have to skip py310-zip because its version of pycairo has a Windows-specific
      # bug. I'm not sure why py36-pip fails.
      - C:\Python310\python.exe -m tox -e "py{37,38,39}-{pip,zip},py310-pip,py36-zip" --parallel 2

    on_finish:
      - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

  -
    matrix:
      only:
        - job_name: macOS Tests

    install:
      # Force install xorgproto, which is a dependency of cairo but can't be linked by
      # homebrew because of a conflicting file.
      - brew install -f --overwrite xorgproto
      - brew install cairo pkg-config
      - export PYBIN=~/venv3.10/bin/python
      - $PYBIN -m pip install -U pip
      - $PYBIN -m pip install tox twine build
      # Put /usr/local/bin at the front of PATH so that homebrew's pkg-config will
      # be run by pip. On 27 Aug 2021, with
      # the default PATH value, `which pkg-config` returned
      # /Library/Frameworks/Mono.framework/Home/bin/pkg-config
      - export PATH=/usr/local/bin:$PATH

    before_test:
      - export PATH=$PATH:~/venv3.6/bin/:~/venv3.7/bin/:~/venv3.8/bin/:~/venv3.9/bin/:~/venv3.10/bin/
      - $PYBIN build/build.py

    test_script:
      - $PYBIN -m tox --parallel 2

    # on_finish:
    #   - export APPVEYOR_SSH_BLOCK=true
    #   - curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
