branches:
  only:
    - master

# cache: .tox

environment:
  SDL_VIDEODRIVER: dummy

  AWS_ACCESS_KEY_ID:
    secure: 3BNx+Qb95vjwu5E6CbX9mrQ8X4EboF4dzt9Ei7Wc4QU=

  AWS_SECRET_ACCESS_KEY:
    secure: bkPtYZvL3Asozn/udXEZChW2gqT/GEJ66xdf+OeMtn4faZR36uKoP2x+wgCp0enQ

  PYPI_TEST_USERNAME: __token__

  PYPI_TEST_PASSWORD:
    secure: > 
      ES1+Jf/JRtml7urHLDaPvnLhtt+unOq+xGbT7xl53qJ31yq2f/o9bj82eG4WFhDaDq2+dD55t
      5DW69oklIm2ePcDoMrW61gar5Wbnhe4a+pDAlS1qA0AJQkb2mOqq80Uqfn7fhZn7u0irgzrlq
      Tj22sBGkbUfzIPsG1HBzPfQof44JVO+mDmWQKEwmw1Wh4rf0ATWeVvIzWZazbjEnhlwbP7Uya
      2wrcJy8UUiAzatdEjRbLSuLSu52MCL8gS9s785KVF0u+8dH00Gaer1cx2dQnk35WtUmkdkzPO
      81Vm+q8=

  # Uncomment and insert your device's public SSH key here to access the 
  # Mac build image.
  APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9Rkdcjvu0MQOMOqlpa5J757pso3iPzMOt6WK3WgJW0kZl/6l/UZfjN9fgJ6PXhtSQkXgyvOrhuyMVdIZIstdbZKnpC6KV274gof44653ildsK3wPSpuF2v9lmPPvfQWyHCfjb19T06p4Rh5idUmZqPXtMFNWL2vSR4IGBE90JlaNOdXDU07KPVkjbb5vsQLh/vl47N2LjU4vDCqHscQ+wVJuExE63vVuv2T3SDYJNpjAuvLZStdIjOjTyRaJHq2uazfajaKK1Ss3IUgvWnfFqg7WD9zASC9VffxZd9mvP1PtAODIPENdZWNFODsdIlSHTwAdO3DhWbwaDS+nfDhgB evan@Evans-MBP.wv.cc.cmu.edu
  APPVEYOR_SSH_BLOCK: true

  matrix:
    # - job_name: Windows Tests
    #   appveyor_build_worker_image: Visual Studio 2019

    - job_name: macOS Tests and Load Artifacts
      appveyor_build_worker_image: macOS

matrix:
  fast_finish: true

build: off

# Uncomment ME to open a remote desktop connection for debugging the 
# Windows tests
# on_finish:
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# Uncomment ME to open an SSH connection for debugging the Mac OS tests
on_finish:
  - sh: export APPVEYOR_SSH_BLOCK=true
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -

for:
  # -
  #   matrix:
  #     only:
  #       - job_name: Windows Tests

  #   install:
  #     - pip install tox

  #   test_script:
  #     - python -m tox

  -
    matrix:
      only:
        - job_name: macOS Tests and Load Artifacts

    install:
      - curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
      - python3 -m pip install tox
      - HOMEBREW_NO_AUTO_UPDATE=1 brew install cairo pkg-config
      # Remove all Mono.framework entries from the PATH so that pip will find the right pkg-config
      # binary, now and later when it is installed by tox. On 27 Aug 2021, with
      # the default PATH value, `which pkg-config` returned
      # /Library/Frameworks/Mono.framework/Home/bin/pkg-config
      - "export PATH=`echo ${PATH} | awk -v RS=: -v ORS=: '/Mono.framework/ {next} {print}'`"
      - python3 -m pip install pycairo

    before_test:
      - export PATH=$PATH:~/venv3.5/bin/:~/venv3.6/bin/:~/venv3.7/bin/:~/venv3.8/bin/:~/venv3.9/bin/

    test_script:
      - python3 -m tox --parallel

    after_test:
      - python3 build/release.py

artifacts:
  - path: pypi_upload
    name: PypiUpload
    type: zip
