branches:
  only:
    - master

cache: .tox

environment:
  SDL_VIDEODRIVER: dummy

  AWS_ACCESS_KEY_ID:
    secure: 3BNx+Qb95vjwu5E6CbX9mrQ8X4EboF4dzt9Ei7Wc4QU=

  AWS_SECRET_ACCESS_KEY:
    secure: bkPtYZvL3Asozn/udXEZChW2gqT/GEJ66xdf+OeMtn4faZR36uKoP2x+wgCp0enQ

  PYPI_TEST_USERNAME: __token__

  PYPI_TEST_PASSWORD:
    secure: > 
      ES1+Jf/JRtml7urHLDaPvnLhtt+unOq+xGbT7xl53qJ31yq2f/o9bj82eG4WFhDaDq2+dD55t
      5DW69oklIm2ePcDoMrW61gar5Wbnhe4a+pDAlS1qA0AJQkb2mOqq80Uqfn7fhZn7u0irgzrlq
      Tj22sBGkbUfzIPsG1HBzPfQof44JVO+mDmWQKEwmw1Wh4rf0ATWeVvIzWZazbjEnhlwbP7Uya
      2wrcJy8UUiAzatdEjRbLSuLSu52MCL8gS9s785KVF0u+8dH00Gaer1cx2dQnk35WtUmkdkzPO
      81Vm+q8=

  # Uncomment and insert your device's public SSH key here to access the 
  # Mac build image. (Encrypt it and use the "secure" keyword if you like) :)
  APPVEYOR_SSH_KEY:
    secure: >
      zZscbW9+BHJ6EFWDMWD3zvRpFAFmBa+ljHPSHmhPbJxpOTXy2hg2eFqJqCE4J47dAPTKReskP
      WofZJjrWMGC43W/YCLX/I5zBkzRpvguURoovIMOaD4Vse8V2KfhA59npO1kswXYGDNV+WiJqZ
      FpZQSCFjUVFuYpe+fhv0qZZpPKNwoEJDfc5Ew8JMH7j7UIK2yNkIGaqSppWN+LTOL23l4kK+b
      KgBRBKUmJeZk7DjdICZqNSTEQXe+yPercHTHp3s6jLdzhCl2qckOMIuJD7ZY9bPCqcbf2FTcB
      MABUSGPTw6MMFOSO+NojxLRX4NKObK2jQ+Ar0mRDPjoEb6o1WANrT5kZI4/qvdMfo3kpYY7JT
      iIi7eqLRpcLHdoEJFqFSFrTbF8HJIGbXH6BPcoQZ4FVQoO+7aQgbjpP7h8tiSGlZqFhYJgFcW
      Jp/6D2jlYy/VqccYp4wTWToejCDpWCDu4ljfta+FMl5c1CLTXw7WKYiBVcWxLPKY+aZjfJGEN
      6DTM4+bLnKFXfYzDRkvDvqQuuyRnXitl/cDFJROYxkbXS8CkJ6/9OXFxu4l4iCN+MQCYQXI96
      dxJ+JBUlqmy9jk1mjHwjGT8KxFzTJDdLF7riYxPZ4Fxd6T+DlavMcB82/Jmlw7tH0fz3UKVwO
      L1PfEVK6NLoJtfmFZnN+RmFPtOo8SBzsbw/4WTcM56DKQQGnQXcLZtrvtbRFFsVtq7J32ViDN
      9pz7UqQT1edE+3hcuo0AP+OaftiQ4pYcEsrVs5

  matrix:
    # - job_name: Windows Tests
    #   appveyor_build_worker_image: Visual Studio 2019

    - job_name: macOS Tests and Load Artifacts
      appveyor_build_worker_image: macOS

matrix:
  fast_finish: true

build: off

# Uncomment ME to open a remote desktop connection for debugging the 
# Windows tests
# on_finish:
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# Uncomment ME to open an SSH connection for debugging the Mac OS tests
on_finish:
  - sh: export APPVEYOR_SSH_BLOCK=true
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -

for:
  # -
  #   matrix:
  #     only:
  #       - job_name: Windows Tests

  #   install:
  #     - pip install tox

  #   test_script:
  #     - py build/splitversions.py --mode split
  #     - python -m tox
  #     - py build/splitversions.py --mode clean

  -
    matrix:
      only:
        - job_name: macOS Tests and Load Artifacts

    install:
      - pip install tox
      # installing pycairo via brew because pip wants to be difficult
      - brew install py3cairo

    before_test:
      - export PATH=$PATH:~/venv3.6/bin/:~/venv3.7/bin/:~/venv3.8/bin/:~/venv3.9/bin/
      - export PYCAIROPATH=$( python3 build/print_cairo_path.py )

    test_script:
      - python3 build/splitversions.py --mode split
      - python -m tox
      - python3 build/splitversions.py --mode clean

    after_test:
      - python3 build/release.py
