branches:
  only:
    - master

environment:
  SDL_VIDEODRIVER: dummy

  # These variables are defined in the web interface:
  # - PYPI_TEST_TOKEN
  # - PYPI_TOKEN
  # - AWS_ACCESS_KEY_ID
  # - AWS_SECRET_ACCESS_KEY

  # Uncomment and insert your device's public SSH key here to access the
  # Mac build image.
  APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9Rkdcjvu0MQOMOqlpa5J757pso3iPzMOt6WK3WgJW0kZl/6l/UZfjN9fgJ6PXhtSQkXgyvOrhuyMVdIZIstdbZKnpC6KV274gof44653ildsK3wPSpuF2v9lmPPvfQWyHCfjb19T06p4Rh5idUmZqPXtMFNWL2vSR4IGBE90JlaNOdXDU07KPVkjbb5vsQLh/vl47N2LjU4vDCqHscQ+wVJuExE63vVuv2T3SDYJNpjAuvLZStdIjOjTyRaJHq2uazfajaKK1Ss3IUgvWnfFqg7WD9zASC9VffxZd9mvP1PtAODIPENdZWNFODsdIlSHTwAdO3DhWbwaDS+nfDhgB evan@Evans-MBP.wv.cc.cmu.edu

matrix:
  fast_finish: true

image:
  - macOS
  - Visual Studio 2019

for:
  -
    matrix:
      only:
        - image: Visual Studio 2019

    build: off
    install:
      - python3 -m pip install tox

    # on_finish:
    #   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

  -
    matrix:
      only:
        - image: macOS

    install:
      - python3 -m pip install tox
      - brew install cairo pkg-config
      # Remove all Mono.framework entries from the PATH so that pip will find the right pkg-config
      # binary, now and later when it is installed by tox. On 27 Aug 2021, with
      # the default PATH value, `which pkg-config` returned
      # /Library/Frameworks/Mono.framework/Home/bin/pkg-config
      - export PATH=/usr/local/bin:$PATH
      # This might be useful -- it removes all Mono.framework entries from the path
      # - "export PATH=`echo ${PATH} | awk -v RS=: -v ORS=: '/Mono.framework/ {next} {print}'`"
      # - python3 -m pip install pycairo

    # before_test:
    #   - export PATH=$PATH:~/venv3.5/bin/:~/venv3.6/bin/:~/venv3.7/bin/:~/venv3.8/bin/:~/venv3.9/bin/

    on_finish:
      - export APPVEYOR_SSH_BLOCK=true
      - curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -


test_script:
  - python3 -m tox --parallel

after_test:
  - python3 build/release.py
